name = "encrypted group"
author = "encode42"
version = "5.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feef52a9ec8c87438e6febf9d74cc9001edc65db295f856d7688d67371ea468f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.214"
