#反转潜行连锁控制
#客户端配置
#默认潜行时停止连锁。
#Invent control
#Client configuration
#By default, function stops while sneaking
invent_control = true
#创造模式下禁用
#客户端配置
#Disable at creative
#Client configuration
disable_at_creative = true
#最大搜索深度
#服务端配置
#请勿设置过大的数值，以免出现性能问题。
#Maximum search depth
#Server-side configuration
#Do not set too large a number to avoid performance issues.
# Default: 256
# Range: > 0
depth_limit = 128
#最大搜索步数
#服务端配置
#请勿设置过大的数值，以免出现性能问题。
#Search steps limit
#Server-side configuration
#Do not set too large a number to avoid performance issues.
# Default: 1024
# Range: > 0
search_steps_limit = 512
#连锁方块组
#服务端配置
#每个字符串为一组，组内的多个ID或Tag之间用逗号分隔，Tag需要以#开头。
#命名空间为minecraft时命名空间可省略。
#Chained blocks groups
#Server-side configuration
#Each string is a group, separated by a comma between multiple IDs or Tags in the group, and the Tags need to start with #.
#If the namespace is minecraft, the namespace can be omitted.
chained_blocks_groups = [
    "minecraft:oak_log",
    "minecraft:spruce_log",
    "minecraft:birch_log",
    "minecraft:jungle_log",
    "minecraft:acacia_log",
    "minecraft:dark_oak_log",
    "minecraft:mangrove_log",
    "minecraft:cherry_log",
    "minecraft:pale_oak_log",
    "minecraft:crimson_stem",
    "minecraft:warped_stem",
    "#minecraft:coal_ores",
    "#minecraft:iron_ores,minecraft:raw_iron_block",
    "#minecraft:copper_ores,minecraft:raw_copper_block",
    "#minecraft:gold_ores",
    "#minecraft:redstone_ores",
    "#minecraft:emerald_ores",
    "#minecraft:lapis_ores",
    "#minecraft:diamond_ores",
    "minecraft:nether_gold_ore",
    "minecraft:nether_quartz_ore",
    "minecraft:ancient_debris",
    "minecraft:glowstone",
    "abundant_atmosphere:ashroot_log",
    "abundant_atmosphere:gourdrot_log",
    "aether:skyroot_log",
    "aether:golden_oak_log",
    "ars_nouveau:blue_archwood_log",
    "ars_nouveau:red_archwood_log",
    "ars_nouveau:purple_archwood_log",
    "ars_nouveau:green_archwood_log",
    "deep_aether:roseroot_log",
    "deep_aether:yagroot_log",
    "deep_aether:cruderoot_log",
    "deep_aether:conberry_log",
    "deep_aether:sunroot_log",
    "enderscape:veiled_log",
    "enderscape:celestial_stem",
    "enderscape:murublight_stem",
    "gardens_of_the_dead:soulblight_stem",
    "herios_floral_expansion:giant_stem_log",
    "herios_floral_expansion:cut_giant_stem_log",
    "herios_floral_expansion:dried_stem_log",
    "hibernal_herbs:myqueste_log",
    "hybrid-aquatic:driftwood_log",
    "luminous_nether:withered_log",
    "luminous_nether:goldenstem",
    "natures_spirit:redwood_log",
    "natures_spirit:sugi_log",
    "natures_spirit:wisteria_log",
    "natures_spirit:fir_log",
    "natures_spirit:willow_log",
    "natures_spirit:aspen_log",
    "natures_spirit:maple_log",
    "natures_spirit:cypress_log",
    "natures_spirit:olive_log",
    "natures_spirit:ghaf_log",
    "natures_spirit:palo_verde_log",
    "natures_spirit:coconut_log",
    "natures_spirit:cedar_log",
    "natures_spirit:larch_log",
    "natures_spirit:mahogany_log",
    "natures_spirit:saxual_log",
    "sculks_of_arda:sculk_log_log",
    "sculks_of_arda:black_birch_log",
    "sculks_of_arda:wisterya_log",
    "sculks_of_arda:radioactive_balsa_log",
    "sculks_of_arda:sculk_resin_black_birch_log",
    "aether:ambrosium_ore",
    "aether:zanite_ore",
    "aether:arkenium_ore",
    "aether:gravitite_ore",
    "#c:ores/zinc",
    "deep_aether:skyjade_ore",
    "enderscape:shadoline_ore",
    "enderscape:mirestone_shadoline_ore",
    "enderscape:nebulite_ore",
    "enderscape:mirestone_nebulite_ore",
    "sculks_of_arda:resin_ancient_granite",
    "sculks_of_arda:sacred_obsidian_ore",
    "sculks_of_arda:deep_granulite_amethys_ore",
    "sculks_of_arda:deep_granulite_sculkerite_ore",
    "sculks_of_arda:ancient_magma",
    "sculks_of_arda:diamond_sculk_ore",
    "sculks_of_arda:gold_sculk_ore",
    "sculks_of_arda:emerald_sculk_ore",
    "sculks_of_arda:quartz_sculk_ore",
    "sculks_of_arda:deep_granulite_gold_ore",
    "sculks_of_arda:deep_granulite_diamond_ore",
    "sculks_of_arda:deep_granulite_ancient_debris_ore",
    "sculks_of_arda:deep_granulite_emerald_ore"
]
