version = 1
enableSodiumMenu = false
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
rpg_companions_tiny_dragons = true
someassemblyrequired = true
storagedrawers = true
aether_beyond_parity = true
abundant_atmosphere = true
chimes = true
etched = true
golemoverhaul = true
dungeonsdelight = true
natures_spirit = true
sootychimneys = true
dye_depot = true
aether = true
the_bumblezone = true
mynethersdelight = true
hearthandharvest = true
valheim_delight = true
drill_drain = true
gardens_of_the_dead = true
exposure = true
hybrid-aquatic = true
endersdelight = true
nightlights = true
hibernalherbs = true
create_vibrant_vaults = true
createbb = true
createrailwaysnavigator = true
minersdelight = true
endrem = true
create = true
yungscavebiomes = true
frightsdelight = true
createadditionallogistics = true
createenchantablemachinery = true
minecraft = true
create_connected = true
cocktailsdelight = true
natures_delight = true
unusual_furniture = true
toxony = true
cuisinedelight = true
refinedstorage = true
trading_floor = true
createaddition = true
ipla = true
createframed = true
dragonlib = true
creeperoverhaul = true
illagerinvasion = true
luminous_nether = true
sculks_of_arda = true
create_factory_logistics = true
trailandtales_delight = true
tuttasdoors = true
ribbits = true
oceansdelight = true
brewinandchewin = true
charta = true
luminous_butterflies = true
youkaishomecoming = true
create_extra_casing = true
veggiesdelight = true
createdieselgenerators = true
create_enchantment_industry = true
white_pumpkins = true
kobolds = true
gemforged = true
fruitsdelight = true
block_factorys_bosses = true
relics = true
graveyard = true
backpacked = true
decobuild = true
enderscape = true
cratedelight = true
create_hypertube = true
glow = true
corn_delight = true
ubesdelight = true
winterly = true
dye_the_world = true
create_colored = true
deep_aether = true
arsdelight = true
refinedtypes = true
stardew_fishing = true
create_dragons_plus = true
herios_floral_expansion = true
pottery = true
create_things_and_misc = true
endermanoverhaul = true
crabbersdelight = true
ars_nouveau = true
rocks = true
crittersandcompanions = true
aethersdelight = true
barbequesdelight = true
pipeorgans = true
pizzadelight = true
eastersdelight = true
netherdepthsupgrade = true
create_integrated_farming = true
