#Minecraft server properties
#Thu Jul 17 19:07:20 UTC 2025
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=hard
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=bundle-backportish\:rabbithide,tectonic\:tectonic,trailiertales\:stronghold_catacombs
initial-enabled-packs=vanilla,fabric,accessories,affinity,alchimiae,amplified_nether,another_furniture,blahaj,bountifulfares,bundle-backportish,cerulean,colorful_books,copperhopper,copperrails,cratedelight,elemental_wizards_rpg,emi_loot,enderscape,fabric-convention-tags-v2,fastitemframes,fletching-expanded,florum-sporum,frozenlib,geophilic,goop,guarding,hearths,hibernalherbs,hopobettermineshaft,hopobetterruinedportal,hopobetterunderwaterruins,immersivelanterns,improved_village_placement,libertyvillagers,lithostitched,missingwilds,more_rpg_classes,mr_lukis_ancientcities,mr_lukis_crazychambers,mr_lukis_grandcapitals,patchouli,perfect-parity-pg,perfectparity,pierced,revamped_shipwrecks,runes,server_translations_api,sketch,smallships,spell_engine,spell_power,starcaller,structory,takesapillage,tclayer,terrablender,trailiertales,underground_rivers,village_taverns,wizards,enderscape\:fix_vanilla_recipes,enderscape\:new_end_cities,enderscape\:fix_levitation_advancement,enderscape\:new_terrain
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=starting up...
network-compression-threshold=256
online-mode=true
op-permission-level=3
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=6
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=false
text-filtering-config=
use-native-transport=true
view-distance=16
white-list=true
